# Generated by Django 4.2 on 2023-04-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designatio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('designation', models.CharField(max_length=20)),
            ],
        ),
    ]
