# Generated by Django 4.2 on 2023-04-26 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_designatio'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Designatio',
            new_name='Designation',
        ),
    ]
