# Generated by Django 4.2 on 2023-04-26 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_customer_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='designation',
            field=models.ForeignKey(default='Customer', null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.designation'),
        ),
    ]
